import {it,expect} from 'vitest';import {createRequire} from 'node:module';import {createHash} from 'node:crypto';
const require=createRequire(import.meta.url);const {performCommunicationSend,reconcilePendingSend}=require('../src/hh-communication-send');
const text='  exact material https://example.com/guide\n'+'я'.repeat(3000)+'\nEND  ';
function fixture(){const history={messages:[],communication_steps:{message:text,material:{stage_id:'arbitrary',hash:'stage-revision'},conversation_revision:'context-1',goal:{execution:{type:'send_material'}}}};let stored,sends=0;return{history,get stored(){return JSON.parse(stored)},get sends(){return sends},options:{history,message:text,source:'mcp',persist:()=>{stored=JSON.stringify(history)},send:async()=>{sends++;return{id:'hh-1'}},refresh:async()=>{history.messages.push({role:'employer',text,hh_id:'hh-1'})}}};}
it('persists pending before POST and verifies exact material provider ID/hash/stage/revision',async()=>{const f=fixture();f.options.send=async()=>{expect(f.stored.communication_send_events[0].status).toBe('pending');return{id:'hh-1'}};const result=await performCommunicationSend(f.options);expect(result.event).toMatchObject({stage_id:'arbitrary',material_revision:'stage-revision',material_hash:createHash('sha256').update(text).digest('hex'),provider_message_id:'hh-1',verification:'provider_history',status:'delivered'});expect(f.stored.communication_send_events).toHaveLength(1);});
it('a transport timeout reconciles delivery without another POST and survives restart/reset',async()=>{const f=fixture();let sends=0;f.options.send=async()=>{sends++;throw Object.assign(new Error('timeout'),{code:'ETIMEDOUT'})};const result=await performCommunicationSend(f.options);expect(result.reconciled).toBe(true);expect(sends).toBe(1);const history=f.stored;delete history.ats_result;const second=await performCommunicationSend({...f.options,history,persist:()=>{}});expect(second.reconciled).toBe(true);expect(sends).toBe(1);expect(history.communication_send_events[0].provider_message_id).toBe('hh-1');});
it('an empty POST response is confirmed by actual provider history, not a local echo',async()=>{const f=fixture();f.options.send=async()=>({});const result=await performCommunicationSend(f.options);expect(result.event.verification).toBe('provider_history');expect(result.sent.id).toBe('hh-1');});
it('old same-text provider messages and unconfirmed local echoes cannot prove uncertain delivery',async()=>{const f=fixture();f.history.messages=[{role:'employer',text,hh_id:'old-id'},{role:'employer',text,hh_id:null}];f.options.send=async()=>{throw new Error('timeout')};f.options.refresh=async()=>{};await expect(performCommunicationSend(f.options)).rejects.toMatchObject({code:'SEND_OUTCOME_UNKNOWN'});expect(f.stored.communication_send_events[0]).toMatchObject({status:'uncertain',verification:'not_found_in_provider_history'});let posts=0;await expect(performCommunicationSend({...f.options,send:async()=>{posts++;}})).rejects.toMatchObject({code:'SEND_OUTCOME_UNKNOWN'});expect(posts).toBe(0);});
it('a crashed pending operation is reconciled before retry and a later provider record heals it',async()=>{const f=fixture();f.options.refresh=async()=>{throw new Error('HH down')};await performCommunicationSend(f.options); // provider ACK is still success
 const history=f.stored;history.communication_send_events[0].status='pending';history.communication_send_events[0].provider_message_id=null;history.messages=[];await expect(reconcilePendingSend({...f.options,history})).rejects.toMatchObject({code:'SEND_OUTCOME_UNKNOWN'});
 const reconciled=await reconcilePendingSend({...f.options,history,refresh:async()=>{history.messages.push({role:'employer',text,hh_id:'actual'})},persist:()=>{}});expect(reconciled.delivered).toBe(true);expect(reconciled.event.provider_message_id).toBe('actual');});
it('explicit resend after a new request gets its own event and provider ID',async()=>{const f=fixture();await performCommunicationSend(f.options);f.history.communication_steps.conversation_revision='context-2';f.history.communication_steps.goal.execution.resend_requested=true;f.options.send=async()=>({id:'hh-2'});f.options.refresh=async()=>{f.history.messages.push({role:'employer',text,hh_id:'hh-2'})};await performCommunicationSend(f.options);expect(f.history.communication_send_events).toHaveLength(2);expect(f.history.communication_send_events.map(e=>e.provider_message_id)).toEqual(['hh-1','hh-2']);});
it('an accidental material repetition under a new context cannot create another POST',async()=>{const f=fixture();await performCommunicationSend(f.options);f.history.communication_steps.conversation_revision='context-2';let posts=0;const repeated=await performCommunicationSend({...f.options,send:async()=>{posts++;}});expect(repeated.reconciled).toBe(true);expect(posts).toBe(0);expect(f.history.communication_send_events).toHaveLength(1);});

it('a retry on the idempotent HH chat path reuses the original UUID after an uncertain result',async()=>{const f=fixture();let visible=false;f.options.refresh=async()=>{if(visible)f.history.messages.push({role:'employer',text,hh_id:'hh-idempotent'})};f.options.send=async()=>{throw Object.assign(new Error('socket timeout'),{code:'ETIMEDOUT'})};await expect(performCommunicationSend(f.options)).rejects.toMatchObject({code:'SEND_OUTCOME_UNKNOWN'});const key=f.stored.communication_send_events[0].id;let retries=0;const retried=await performCommunicationSend({...f.options,retryUncertain:true,send:async event=>{retries++;expect(event.id).toBe(key);visible=true;throw Object.assign(new Error('HH API 409: duplicate idempotency_key'),{status:409})}});expect(retries).toBe(1);expect(retried.reconciled).toBe(true);expect(retried.event.id).toBe(key);expect(retried.event.provider_message_id).toBe('hh-idempotent');});

it('an empty-string provider ID cannot masquerade as positive delivery',async()=>{const f=fixture();f.options.send=async()=>({id:''});f.options.refresh=async()=>{};await expect(performCommunicationSend(f.options)).rejects.toMatchObject({code:'SEND_OUTCOME_UNKNOWN'});expect(f.stored.communication_send_events[0].status).toBe('uncertain');});
