import {it,expect} from 'vitest';import {createRequire} from 'node:module';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';
const require=createRequire(import.meta.url);const {startMcp}=require('./helpers/mcp');
it('real MCP standalone, regeneration and review use provider full history and resume with scoped Communication and no ATS-score prerequisite',async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'hh-mcp-plan-paths-'));const user='fixture',vacancy='target';const workDir=path.join(root,'users',user);const ctx=path.join(workDir,'contexts','hh');fs.mkdirSync(ctx,{recursive:true});const put=(key,value)=>fs.writeFileSync(path.join(ctx,key+'.json'),JSON.stringify({value}));
 const ats={vacancy_id:vacancy,vacancy_title:'Дизайнер',required:[],preferred:[],communication_plan:{version:1,stages:[{id:'portfolio',title:'Портфолио',instruction:'Получи портфолио',completion_result:'Ссылка или файл получены',material:'',material_mode:'context'}]}};put('ats_config:'+vacancy,ats);put('active_vacancy',{id:'another',title:'Другой проект'});
 const tokens=path.join(root,'tokens',user);fs.mkdirSync(tokens,{recursive:true});fs.writeFileSync(path.join(tokens,'hh'),JSON.stringify({access_token:'fixture-only'}),{mode:0o600});
 const requests=[],communication=[];const resumeText='Полное описание опыта '.repeat(140);const negotiation=id=>({id,vacancy:{id:vacancy},resume:{id:'resume-'+id,first_name:'Анна',last_name:'Тест'},updated_at:'2026-10-05T00:00:00Z',chat_id:'chat-'+id,state:{id:'consider'}});
 const server=http.createServer(async(req,res)=>{let raw='';for await(const c of req)raw+=c;requests.push({path:req.url,method:req.method});const url=new URL(req.url,'http://fixture');let out;
  if(req.url.startsWith('/v1/')){const input=JSON.parse(raw);communication.push({path:req.url,input});res.setHeader('x-contract-version','v1');if(req.url.endsWith('/state/extract')){out={conversation_revision:input.conversation_revision,state:{summary:'Портфолио получено, рекрутер должен ответить',contact_allowed:true,stages:[{stage_id:'portfolio',status:'completed',evidence:[{source_id:'old-answer',quote:'Портфолио https://example.com/anna'}]}],requirements:[],open_questions:[],uncertainties:[],next_check_at:null}};}else if(req.url.endsWith('/next-goal'))out={conversation_revision:input.conversation_revision,status:'goal_ready',requires_message:true,reason:'Ответить на полученное портфолио',goal:{instruction:'Поблагодари кандидата за присланное портфолио'},execution:{type:'write_message'}};else out={context_revision:input.context_revision,status:'generated',message_text:'Спасибо, портфолио получили.'};
  }else if(url.pathname==='/negotiations/response')out={items:[negotiation('regen')],pages:1};else if(url.pathname.startsWith('/negotiations/'))out=negotiation(url.pathname.split('/')[2]);else if(url.pathname.startsWith('/resumes/'))out={id:url.pathname.split('/')[2],first_name:'Анна',last_name:'Тест',skills:resumeText};else if(url.pathname.startsWith('/common/chats/'))out=url.searchParams.get('start_message_id')?{messages:[{id:'old-answer',creation_time:'2026-10-01T00:00:00Z',payload:{text:'Портфолио https://example.com/anna'},sender_display_info:{role:'APPLICANT'}}],has_more:false}:{messages:[{id:'recent',creation_time:'2026-10-05T00:00:00Z',payload:{text:'Добрый день'},sender_display_info:{role:'APPLICANT'}}],has_more:true};else{res.writeHead(500);res.end(JSON.stringify({error:'Unexpected fixture request'}));return;}
  res.setHeader('content-type','application/json');res.end(JSON.stringify(out));
 });await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;let mcp;
 try{mcp=await startMcp({userId:user,workDir,env:{HOME:root,AGENT_DATA_DIR:path.join(root,'data'),USERS_DIR:path.join(root,'users'),AGENT_TOKENS_ROOT:path.join(root,'tokens'),AGENT_TOKENS_DIR:path.join(root,'tokens'),HH_API_BASE_URL:base,HH_COMMUNICATION_ENABLED:'1',HH_COMMUNICATION_USERS:user,HH_COMMUNICATION_VACANCIES:vacancy,COMMUNICATION_API_URL:base,COMMUNICATION_TOKEN:'fixture-only',LLM_LADDER_TOKEN:'fixture-unused',LLM_LADDER_BASE_URL:base}});
  const call=async(name,args)=>{const result=await mcp.call('tools/call',{name,arguments:args});return JSON.parse(result.content[0].text);};
  const single=await call('hh_generate_message_to_applicant',{negotiation_id:'standalone'});expect(single.message,single.error).toBe('Спасибо, портфолио получили.');
  const regenerated=await call('hh_regenerate_messages',{vacancy_id:vacancy});expect(regenerated.regenerated,JSON.stringify(regenerated)).toBe(1);
  const page=await call('hh_draft_review_page',{vacancy_id:vacancy,vacancy_name:'Дизайнер',candidates:[{negotiation_id:'review',name:'Анна Тест',verdict:'УТОЧНИТЬ'}]});expect(page.error).toBeUndefined();
  expect(communication.filter(c=>c.path.endsWith('/state/extract'))).toHaveLength(3);for(const c of communication.filter(c=>c.path.endsWith('/state/extract'))){expect(c.input.partner_profile.text).toContain(resumeText);expect(c.input.conversation_history.messages.map(m=>m.text)).toContain('Портфолио https://example.com/anna');}expect(communication.filter(c=>c.path.endsWith('/next-message'))).toHaveLength(3);expect(requests.some(r=>r.path.includes('chat/completions'))).toBe(false);expect(requests.filter(r=>r.method==='POST').every(r=>r.path.startsWith('/v1/'))).toBe(true);
 }finally{if(mcp)await mcp.stop();await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});}
},20000);
