import {it,expect} from 'vitest';import {createRequire} from 'node:module';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {Readable} from 'node:stream';
const require=createRequire(import.meta.url);const {handleHhPublic}=require('../src/hh-routes');const {contactForbidden}=require('../src/hh-communication-runtime');
it('candidate test-task refusal is not a blanket contact ban',()=>expect(contactForbidden({communication_steps:{state:{state:{contact_allowed:true,summary:'Отказался от тестового'}}}})).toBe(false));
it('explicit contact ban blocks forced HTTP send and send-with-rejection before any HH request',async()=>{
 const keys=['AGENT_DATA_DIR','AGENT_TOKENS_DIR','AGENT_TOKENS_ROOT','AGENT_SECRET','HH_COMMUNICATION_ENABLED','HH_COMMUNICATION_USERS','HH_COMMUNICATION_VACANCIES'];const old=Object.fromEntries(keys.map(k=>[k,process.env[k]]));const root=fs.mkdtempSync(path.join(os.tmpdir(),'hh-contact-ban-'));const originalFetch=globalThis.fetch;let requests=0;globalThis.fetch=async()=>{requests++;throw new Error('HH must not be contacted');};
 try{process.env.AGENT_DATA_DIR=path.join(root,'data');process.env.AGENT_TOKENS_DIR=path.join(root,'tokens');process.env.AGENT_TOKENS_ROOT=path.join(root,'tokens');process.env.AGENT_SECRET='';process.env.HH_COMMUNICATION_ENABLED='1';delete process.env.HH_COMMUNICATION_USERS;delete process.env.HH_COMMUNICATION_VACANCIES;
 const tokenDir=path.join(root,'tokens','alice');fs.mkdirSync(tokenDir,{recursive:true});fs.writeFileSync(path.join(tokenDir,'hh'),JSON.stringify({access_token:'fixture'}),{mode:0o600});const cand=path.join(root,'data','hh','alice','candidates');fs.mkdirSync(cand,{recursive:true});fs.writeFileSync(path.join(cand,'n1.json'),JSON.stringify({messages:[],vacancy_id:'vac',communication_steps:{state:{state:{contact_allowed:false}},goal:{status:'do_not_contact'}}}),{mode:0o600});
 for(const endpoint of ['/hh/send','/hh/send-and-reject']){const body={username:'alice',negotiation_id:'n1',vacancy_id:'vac',message:'Manual message',force:true};const req=Readable.from([Buffer.from(JSON.stringify(body))]);req.method='POST';req.headers={};req.url=endpoint;let status,text;const res={setHeader(){},writeHead(s){status=s},end(b){text=String(b)}};await handleHhPublic(req,new URL(endpoint,'http://localhost'),res,{BASE_USERS_DIR:path.join(root,'users'),getSecretsCache:()=>({}),secrets:{}});expect(status).toBe(409);expect(JSON.parse(text).code).toBe('CONTACT_FORBIDDEN');}expect(requests).toBe(0);
 }finally{globalThis.fetch=originalFetch;for(const[k,v]of Object.entries(old))v===undefined?delete process.env[k]:process.env[k]=v;fs.rmSync(root,{recursive:true,force:true});}
});
