import {it,expect} from 'vitest';import {createRequire} from 'node:module';import {Readable} from 'node:stream';import http from 'node:http';import {execFile} from 'node:child_process';
const require=createRequire(import.meta.url);const {handleHhPublic}=require('../src/hh-routes');const {skillRevision}=require('../src/hh-version');
it('safe invalid POST routes identify the loaded skill revision before credential or model work',async()=>{
 for(const endpoint of ['/hh/ats-config','/hh/generate-message']){const req=Readable.from([Buffer.from('{}')]);req.method='POST';req.headers={};const headers={};let status,body;const res={setHeader(k,v){headers[k.toLowerCase()]=v},writeHead(s){status=s},end(b){body=String(b)}};await handleHhPublic(req,new URL(endpoint,'http://localhost'),res,{getSecretsCache:()=>({}),BASE_USERS_DIR:'/nonexistent-fixture',secrets:{}});expect(status).toBe(400);expect(headers['x-hh-skill-rev']).toBe(skillRevision());expect(JSON.parse(body).error).toBe(endpoint==='/hh/ats-config'?'config required':'missing fields');}
});
it('deployment gate checks editor plus both public POST owners and rejects a competing route',async()=>{
 const revision='a'.repeat(40),requests=[];let competing=false;
 const server=http.createServer(async(req,res)=>{let body='';for await(const c of req)body+=c;requests.push({path:req.url,method:req.method,body});res.setHeader('X-HH-Skill-Rev',competing&&req.url==='/hh/generate-message'?'b'.repeat(40):revision);if(req.method==='GET'){res.end(`<meta name="hh-skill-rev" content="${revision}">`);return;}res.writeHead(400,{'Content-Type':'application/json'});res.end(JSON.stringify({error:req.url==='/hh/ats-config'?'config required':'missing fields'}));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const run=()=>new Promise(resolve=>execFile(process.execPath,['scripts/verify-deploy.cjs','--rev',revision,'--base',`http://127.0.0.1:${server.address().port}`,'--user','fixture','--token','fixture'],{timeout:10000},(error,stdout,stderr)=>resolve({code:error?.code||0,stdout,stderr})));
 try{expect((await run()).code).toBe(0);expect(requests.filter(r=>r.method==='POST').map(r=>({path:r.path,body:r.body}))).toEqual([{path:'/hh/ats-config',body:'{}'},{path:'/hh/generate-message',body:'{}'}]);competing=true;const failure=await run();expect(failure.code).toBe(1);expect(failure.stderr).toContain('/hh/generate-message');}finally{await new Promise(r=>server.close(r));}
},20000);
