import {it,expect} from 'vitest';import {createRequire} from 'node:module';import {Readable} from 'node:stream';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
const require=createRequire(import.meta.url);const {handleHhPublic}=require('../src/hh-routes');const {freshnessSignature}=require('../src/hh-communication-runtime');
it('HTTP persists pending send before POST, reconciles empty HH response by canonical chat, and never resends on retry',async()=>{
 const keys=['AGENT_DATA_DIR','AGENT_TOKENS_DIR','AGENT_TOKENS_ROOT','AGENT_SECRET','HH_COMMUNICATION_ENABLED','HH_COMMUNICATION_USERS','HH_COMMUNICATION_VACANCIES'];const old=Object.fromEntries(keys.map(k=>[k,process.env[k]]));const root=fs.mkdtempSync(path.join(os.tmpdir(),'hh-send-outcome-route-'));const originalFetch=globalThis.fetch;let posts=0;const text='Exact material\n ';const file=path.join(root,'data','hh','alice','candidates','n1.json');
 globalThis.fetch=async(url,options)=>{let body;if(options?.method==='POST'){posts++;expect(JSON.parse(fs.readFileSync(file)).communication_send_events.at(-1).status).toBe('pending');body={};}else if(String(url).includes('/common/chats/'))body={messages:posts?[{id:'delivered-1',creation_time:'2026-10-05T10:00:00Z',payload:{text},sender_display_info:{role:'EMPLOYER'}}]:[],has_more:false};else if(String(url).includes('/resumes/'))body={id:'resume-outcome',first_name:'Анна'};else body={id:'n1',chat_id:'chat',state:{id:'consider'},resume:{id:'resume-outcome'}};return {ok:true,status:200,json:async()=>body};};
 try{process.env.AGENT_DATA_DIR=path.join(root,'data');process.env.AGENT_TOKENS_DIR=path.join(root,'tokens');process.env.AGENT_TOKENS_ROOT=path.join(root,'tokens');process.env.AGENT_SECRET='';process.env.HH_COMMUNICATION_ENABLED='1';delete process.env.HH_COMMUNICATION_USERS;delete process.env.HH_COMMUNICATION_VACANCIES;
 const tokens=path.join(root,'tokens','alice');fs.mkdirSync(tokens,{recursive:true});fs.writeFileSync(path.join(tokens,'hh'),JSON.stringify({access_token:'fixture'}),{mode:0o600});fs.mkdirSync(path.dirname(file),{recursive:true});const snapshot={history:[],atsConfig:{},atsResult:{},resumeText:'Анна',senderProfile:{}};fs.writeFileSync(file,JSON.stringify({messages:[],vacancy_id:'vac',communication_snapshot:snapshot,communication_freshness_sig:freshnessSignature(snapshot),communication_steps:{conversation_revision:'r1',message:text,material:{stage_id:'task',hash:'materialhash'},state:{state:{contact_allowed:true}},goal:{status:'goal_ready'}}}),{mode:0o600});
 for(let attempt=0;attempt<2;attempt++){const req=Readable.from([Buffer.from(JSON.stringify({username:'alice',negotiation_id:'n1',vacancy_id:'vac',message:text}))]);req.method='POST';req.headers={};let status,raw;const res={setHeader(){},writeHead(s){status=s},end(b){raw=String(b)}};await handleHhPublic(req,new URL('/hh/send','http://localhost'),res,{BASE_USERS_DIR:path.join(root,'users'),getSecretsCache:()=>({}),secrets:{}});expect(status).toBe(200);expect(JSON.parse(raw).ok).toBe(true);}
 expect(posts).toBe(1);const stored=JSON.parse(fs.readFileSync(file));expect(stored.communication_send_events).toHaveLength(1);expect(stored.communication_send_events[0]).toMatchObject({status:'delivered',verification:'provider_history',provider_message_id:'delivered-1',stage_id:'task'});expect(stored.messages.filter(m=>m.role==='employer')).toHaveLength(1);expect(stored.messages[0].text).toBe(text);
 }finally{globalThis.fetch=originalFetch;for(const[k,v]of Object.entries(old))v===undefined?delete process.env[k]:process.env[k]=v;fs.rmSync(root,{recursive:true,force:true});}
});
