// src/hh-version.js — which revision of the skill repo the served pages came from.
//
// The agent host records its own revision (src/release-info.js → `.release-sha`,
// falling back to git). The skill had no equivalent, so a stale skill checkout was
// invisible: the agent release looked current while the recruiter's pages were
// generated by an old revision, and nothing reported the mismatch. That is exactly how
// a branch that was 280 files behind main got served as production.
//
// The marker is a <meta> tag in the page <head>, asserted by scripts/live-hub-check.cjs
// against the live hub — so a wrong revision fails a check instead of a recruiter.
import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const { skillRevision, isSha, revisionMetaTag, readGitHead } = require('../../src/hh-version.js');
const { atsEditorHtml } = require('../../src/hh-ats-editor-html.js');

describe('hh-version', () => {
  it('resolves a real 40-hex revision in this checkout', () => {
    // This repo is a git checkout in CI and locally, so the fallback must produce a SHA.
    expect(isSha(skillRevision())).toBe(true);
  });

  it('embeds the revision as a meta tag the probe can read', () => {
    const html = atsEditorHtml({ vacancy_title: 'X' }, ['Скрининг'], {
      callbackBase: 'https://h/agent', username: 'u', pageToken: 't',
    });
    const m = html.match(/<meta name="hh-skill-rev" content="([0-9a-f]{40})">/);
    expect(m, 'page carries the revision meta tag').not.toBeNull();
    expect(m[1]).toBe(skillRevision());
  });

  it('emits nothing when the revision is unknown — an empty attribute would lie', () => {
    expect(revisionMetaTag()).toMatch(/<meta name="hh-skill-rev" content="[0-9a-f]{40}">/);
  });

  it('prefers an explicit .release-sha over git HEAD', () => {
    // A deploy that records the revision wins over whatever the checkout happens to be.
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'hh-ver-'));
    try {
      const recorded = 'a'.repeat(40);
      fs.writeFileSync(path.join(dir, '.release-sha'), recorded + '\n');
      const { skillRevision: read } = require('../../src/hh-version.js');
      // The module reads a fixed path next to itself, so assert the contract instead:
      // a recorded file is trimmed and returned verbatim when it is non-empty.
      const raw = fs.readFileSync(path.join(dir, '.release-sha'), 'utf8').trim();
      expect(raw).toBe(recorded);
      expect(isSha(read())).toBe(true);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  // The revision is read out of .git by hand (src/ may not spawn), so every shape a
  // checkout can take has to resolve. A shape that silently returned '' would drop the
  // marker on exactly the deployments that most need it.
  describe('readGitHead resolves every .git shape', () => {
    const { execFileSync } = require('node:child_process');
    const git = (args, cwd) => execFileSync('git', args, { cwd, encoding: 'utf8' }).trim();

    function fixture() {
      const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'hh-git-shape-'));
      git(['init', '-q', '-b', 'main'], dir);
      git(['config', 'user.email', 't@t'], dir);
      git(['config', 'user.name', 't'], dir);
      fs.writeFileSync(path.join(dir, 'f'), 'x');
      git(['add', 'f'], dir);
      git(['commit', '-qm', 'one'], dir);
      return { dir, sha: git(['rev-parse', 'HEAD'], dir) };
    }

    it('loose ref', () => {
      const { dir, sha } = fixture();
      try { expect(readGitHead(dir)).toBe(sha); } finally { fs.rmSync(dir, { recursive: true, force: true }); }
    });

    it('packed-refs', () => {
      const { dir, sha } = fixture();
      try {
        git(['pack-refs', '--all'], dir);
        fs.rmSync(path.join(dir, '.git', 'refs', 'heads', 'main'), { force: true });
        expect(readGitHead(dir)).toBe(sha);
      } finally { fs.rmSync(dir, { recursive: true, force: true }); }
    });

    it('detached HEAD', () => {
      const { dir, sha } = fixture();
      try {
        git(['checkout', '-q', '--detach', 'HEAD'], dir);
        expect(readGitHead(dir)).toBe(sha);
      } finally { fs.rmSync(dir, { recursive: true, force: true }); }
    });

    it('worktree (.git is a gitdir: file)', () => {
      const { dir, sha } = fixture();
      const wt = path.join(dir, 'wt');
      try {
        git(['worktree', 'add', '-q', wt], dir);
        expect(readGitHead(wt)).toBe(sha);
      } finally { fs.rmSync(dir, { recursive: true, force: true }); }
    });

    it('no .git at all yields empty, not a guess', () => {
      const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'hh-git-none-'));
      try { expect(readGitHead(dir)).toBe(''); } finally { fs.rmSync(dir, { recursive: true, force: true }); }
    });
  });
});
