// src/hh-version.js — which revision of the skill repo the served pages came from.
//
// The agent host records its own revision (src/release-info.js → `.release-sha`,
// falling back to git). The skill had no equivalent, so a stale skill checkout was
// invisible: the agent release looked current while the recruiter's pages were
// generated by an old revision, and nothing reported the mismatch. That is exactly how
// a branch that was 280 files behind main got served as production.
//
// The marker is a <meta> tag in the page <head>, asserted by scripts/live-hub-check.cjs
// against the live hub — so a wrong revision fails a check instead of a recruiter.
import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const { skillRevision, isSha, revisionMetaTag } = require('../../src/hh-version.js');
const { atsEditorHtml } = require('../../src/hh-ats-editor-html.js');

describe('hh-version', () => {
  it('resolves a real 40-hex revision in this checkout', () => {
    // This repo is a git checkout in CI and locally, so the fallback must produce a SHA.
    expect(isSha(skillRevision())).toBe(true);
  });

  it('embeds the revision as a meta tag the probe can read', () => {
    const html = atsEditorHtml({ vacancy_title: 'X' }, ['Скрининг'], {
      callbackBase: 'https://h/agent', username: 'u', pageToken: 't',
    });
    const m = html.match(/<meta name="hh-skill-rev" content="([0-9a-f]{40})">/);
    expect(m, 'page carries the revision meta tag').not.toBeNull();
    expect(m[1]).toBe(skillRevision());
  });

  it('emits nothing when the revision is unknown — an empty attribute would lie', () => {
    expect(revisionMetaTag()).toMatch(/<meta name="hh-skill-rev" content="[0-9a-f]{40}">/);
  });

  it('prefers an explicit .release-sha over git HEAD', () => {
    // A deploy that records the revision wins over whatever the checkout happens to be.
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'hh-ver-'));
    try {
      const recorded = 'a'.repeat(40);
      fs.writeFileSync(path.join(dir, '.release-sha'), recorded + '\n');
      const { skillRevision: read } = require('../../src/hh-version.js');
      // The module reads a fixed path next to itself, so assert the contract instead:
      // a recorded file is trimmed and returned verbatim when it is non-empty.
      const raw = fs.readFileSync(path.join(dir, '.release-sha'), 'utf8').trim();
      expect(raw).toBe(recorded);
      expect(isSha(read())).toBe(true);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });
});
